
io:
  portfolio_cache: "portfolio/portfolio_cache"
  profile_out_dir: "."

# kernel engine is "C" or "PY"
kernel:
  engine: "PY"  # "PY"   # "C"
  max_age: 120

model:
  type: "GenericMultiState"
  years_to_simulate: 119
  steps_per_month: 1
  use_multicore: true

run_type_specs:

  GenericMultiState:
    state_model: "AnnuityRunoffStates"
    assumptions_spec: "longevity_assumptions_simple.yml"
    outfile: "results/ncf_out_generic.csv"
    portfolio_path: "portfolio/portfolio_annuity_small.xlsx"
    # sportfolio_path: "portfolio/portfolio_annuity_med.xlsx"
    portfolio_chunk_size: 400000
