
io:
  portfolio_cache: "portfolio/portfolio_cache"
  profile_out_dir: "."

kernel:
  engine: "PY"  # "PY" or "C"
  max_age: 120

model:
  # Type of Model to be run, only supported type is "GenericMultiState"  
  type: "GenericMultiState"
  years_to_simulate: 119
  steps_per_month: 1
  use_multicore: false   # true    # false

run_type_specs:
  GenericMultiState:
    # for the generic model a state model is required, either "MultiStateDisabilityStates" or "AnnuityRunoffStates"
    state_model: "AnnuityRunoffStates"
    assumptions_spec: "longevity_assumptions.yml"
    outfile: "results/ncf_out_generic.csv"
    portfolio_path: "portfolio/portfolio_annuity_small.xlsx"
    portfolio_chunk_size: 1024
