
io:
  portfolio_cache: "portfolio/portfolio_cache"
  profile_out_dir: "."

kernel:
  engine: "PY"  # "PY" or "C"
  max_age: 120

model:
  type: "GenericMultiState"
  years_to_simulate: 121
  steps_per_month: 1
  use_multicore: false


run_type_specs:

  GenericMultiState:
    state_model: "MortalityStates2"
    assumptions_spec: "mortality_assumptions_simple.yml"
    outfile: "results/ncf_out_generic.csv"
    portfolio_path: "portfolio/portfolio_small.xlsx"
    portfolio_chunk_size: 1024
