
io:
  portfolio_cache: "portfolio/portfolio_cache"
  profile_out_dir: "."

kernel:
  engine: "C"  # "PY" or "C"
  max_age: 120

model:
  # Type of Model to be run, only supported type is "GenericMultiState"  
  type: "GenericMultiState"
  years_to_simulate: 121
  steps_per_month: 1
  use_multicore: true


run_type_specs:
  GenericMultiState:
    state_model: "MortalityStates"
    assumptions_spec: "mortality_assumptions_simple.yml"
    outfile: "results/ncf_out_generic.csv"
    # portfolio_path: "portfolio/portfolio_small_cli.xlsx"
    portfolio_path: "portfolio/portfolio_med_cli.xlsx"
    # portfolio_path: "portfolio/portfolio_big_cli.xlsx"
    portfolio_chunk_size: 10000
